/**
 * rolePermissions.ts — SINGLE SOURCE OF TRUTH for the RBAC permission matrix.
 *
 * CLAUDE.md Section 5 + Section 3.5-B:
 *   "Build a single rolePermissions.ts config used by both auth.ts middleware on
 *    the backend and route guards on the frontend so this matrix lives in exactly
 *    one place. Do not hardcode role checks scattered across controllers."
 *
 * FRONTEND DUPLICATE — auto-generated from backend/src/config/rolePermissions.ts.
 * DO NOT EDIT THIS FILE DIRECTLY. Edit backend/src/config/rolePermissions.ts
 * and update this file in the same commit so they never drift.
 *
 * Aryan: import { canAccess, rolePermissions, ALL_ROLES } from '@/config/rolePermissions'
 * in AuthContext.tsx and your route guards.
 */

export type Role =
  | 'Fleet Manager'
  | 'Dispatcher'
  | 'Safety Officer'
  | 'Financial Analyst';

export type Module = 'fleet' | 'drivers' | 'trips' | 'fuel' | 'analytics';

export type PermissionLevel = 'full' | 'view' | 'none';

/**
 * The authoritative RBAC matrix from CLAUDE.md Section 5.
 *
 * | Role              | Fleet | Drivers | Trips | Fuel/Exp | Analytics |
 * |---|---|---|---|---|---|
 * | Fleet Manager     | full  | full    | none  | none     | full      |
 * | Dispatcher        | view  | none    | full  | none     | none      |
 * | Safety Officer    | none  | full    | view  | none     | none      |
 * | Financial Analyst | view  | none    | none  | full     | full      |
 */
export const rolePermissions: Record<Role, Record<Module, PermissionLevel>> = {
  'Fleet Manager': {
    fleet: 'full',
    drivers: 'full',
    trips: 'none',
    fuel: 'none',
    analytics: 'full',
  },
  Dispatcher: {
    fleet: 'view',
    drivers: 'none',
    trips: 'full',
    fuel: 'none',
    analytics: 'none',
  },
  'Safety Officer': {
    fleet: 'none',
    drivers: 'full',
    trips: 'view',
    fuel: 'none',
    analytics: 'none',
  },
  'Financial Analyst': {
    fleet: 'view',
    drivers: 'none',
    trips: 'none',
    fuel: 'full',
    analytics: 'full',
  },
};

export const getPermission = (role: Role, module: Module): PermissionLevel => {
  return rolePermissions[role]?.[module] ?? 'none';
};

export const canAccess = (
  role: Role,
  module: Module,
  requiredLevel: 'full' | 'view'
): boolean => {
  const level = getPermission(role, module);
  if (level === 'none') return false;
  if (requiredLevel === 'view') return level === 'view' || level === 'full';
  if (requiredLevel === 'full') return level === 'full';
  return false;
};

export const ALL_ROLES: Role[] = [
  'Fleet Manager',
  'Dispatcher',
  'Safety Officer',
  'Financial Analyst',
];

export const ALL_MODULES: Module[] = [
  'fleet',
  'drivers',
  'trips',
  'fuel',
  'analytics',
];
